msg = str(input('Digite qualquer coisa: '))
print(f'Quantos caracteres totais: {len(msg)}')
print(f'É uma frase numérica? {msg.isnumeric()}')
print(f'É alfanumérica? {msg.isalnum()}')
print(f'É alfabética? {msg.isalpha()}')
print(f'Só tem espaços? {msg.isspace()}')
print(f'Está capitalizado? {msg.isidentifier()}')
print(f'Está em maiúsculo? {msg.isupper()}')
print(f'EStá em minúsculo? {msg.islower()}')
